const stickers = [{
    id: 1,
    name: 'star',
    category: 'space',
    url: '',
    inStock: true,
    inventory: 5,
    labelType: "vinyl",
    width: 2.5,
    height: 2.5,
    shape: "square",
}, 
{
    id: 2,
    name: 'bird',
    category: 'animal',
    url: '',
    inStock: true,
    inventory: 2,
    labelType: "polyester",
    width: 2,
    height: 2,
    shape: "circle",
},
{
    id: 3,
    name: 'bmw',
    category: 'vehicle',
    url: '',
    inStock: true,
    inventory: 2,
    labelType: "polyester",
    width: 2,
    height: 2,
    shape: "circle",
},
{
    id: 4,
    name: 'eggs',
    category: 'food',
    url: '',
    inStock: true,
    inventory: 2,
    labelType: "polyester",
    width: 2,
    height: 2,
    shape: "circle",
},
{
    id: 5,
    name: 'beach',
    category: 'nature',
    url: '',
    inStock: true,
    inventory: 2,
    labelType: "polyester",
    width: 2,
    height: 2,
    shape: "circle",
}
]

module.exports = {
    stickers
}